[package]
name = "tender"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-width = "0.1.10"
unicode-segmentation = "1.10.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
test-case = "2.2.2"
